<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>DigitalDash</RootNamespace>
		<AssemblyName>DigitalDash</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MicroGauge.Wpf" Version="1.0.1.1" />
		<PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.8" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\**\*.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="Assets\Images\Honda Frankenstein Logo.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Gauge.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Large Tacs.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Medium Tacs.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Needle Center.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Needle.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Numbers.png" />
	  <EmbeddedResource Remove="Assets\Images\Rpm Small Tacs.png" />
	  <EmbeddedResource Remove="Assets\Images\Spd Gauge.png" />
	  <EmbeddedResource Remove="Assets\Images\Spd Large Tacs.png" />
	  <EmbeddedResource Remove="Assets\Images\Spd Medium Tacs.png" />
	  <EmbeddedResource Remove="Assets\Images\Spd Numbers.png" />
	  <EmbeddedResource Remove="Assets\Images\x1000 Rpm.png" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\Fonts\EurostarBlack.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Fonts\EurostarRegular.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Fonts\Orbitron-Medium.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Honda Frankenstein Logo.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Gauge.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Large Tacs.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Medium Tacs.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Needle Center.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Needle.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Numbers.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Rpm Small Tacs.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Spd Gauge.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Spd Large Tacs.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Spd Medium Tacs.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\Spd Numbers.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Images\x1000 Rpm.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>
